/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. The ASF
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.apache.knox.gateway.services.knoxidf.delegation;

import org.apache.knox.gateway.services.Service;

import java.util.Optional;

/**
 * Gateway service that stores and evaluates RFC 8693 delegation policies for Knox IDF.
 */
public interface DelegationPolicyService extends Service {

  /**
   * Registers a new delegation policy. The registrationId is generated by the service.
   * Throws {@link RuntimeException} if the actor (actorAuthority, actorId) is already registered
   * or a storage error occurs.
   */
  DelegationPolicy register(DelegationPolicy policy);

  /**
   * Fully replaces all fields including child rows (users, groups, resource policy).
   * Child rows are deleted and re-inserted transactionally.
   * Throws {@link RuntimeException} on storage error.
   */
  void update(String registrationId, DelegationPolicy policy);

  void delete(String registrationId);

  Optional<DelegationPolicy> get(String registrationId);

  /** Primary lookup used by evaluate() and by the admin API scope-limiting check. */
  Optional<DelegationPolicy> findByActor(String actorAuthority, String actorId);

  /** @param actorAuthorityFilter null returns all policies */
  DelegationPolicyList list(String actorAuthorityFilter);

  PolicyDecision evaluate(PolicyCheckRequest request);
}
