/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. The ASF
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.apache.knox.gateway.services.knoxidf.delegation;

import org.apache.knox.gateway.services.Service;

import java.util.Optional;

/**
 * Gateway service that stores and evaluates RFC 8693 delegation policies for Knox IDF.
 */
public interface DelegationPolicyService extends Service {

  /**
   * Registers a new delegation policy. The registrationId is generated by the service.
   * @throws DelegationPolicyAlreadyExistsException if the actor (actorAuthority, actorId) is
   *     already registered.
   * @throws RuntimeException on any other storage error.
   */
  DelegationPolicy register(DelegationPolicy policy);

  /**
   * Fully replaces all mutable fields (name, status, tokenTtlSec, description,
   * allowHeadlessExchange, canActForUsers, canActForGroups, resourcePolicy) including child rows,
   * which are deleted and re-inserted transactionally. actorAuthority, actorId, createdBy, and
   * createdAt are immutable after registration: they are never written by this call regardless of
   * what {@code policy} carries for them, and updatedAt is computed by the storage layer, not the
   * caller. Returns the persisted policy, reflecting the true (unchanged) identity/creation fields.
   * @throws DelegationPolicyNotFoundException if registrationId does not exist, or if policy's
   *     actorAuthority/actorId do not match the existing record's -- identity cannot be changed
   *     via update; delete and re-register instead. The two causes are deliberately not
   *     distinguished; callers can GET the registrationId separately to tell them apart.
   * @throws RuntimeException on any other storage error.
   */
  DelegationPolicy update(String registrationId, DelegationPolicy policy);

  /**
   * Creates a new delegation policy for (policy.actorAuthority, policy.actorId) if none exists
   * yet, or fully replaces the existing one for that actor if one does (same full-replace
   * semantics as {@link #update(String, DelegationPolicy)} -- see its javadoc). This is the only
   * entry point that does not require the caller to already know registrationId; it exists for
   * callers (e.g. a Kubernetes operator reconciling a CRD) that know only the actor identity and
   * cannot distinguish "first reconcile" from "re-reconcile" without it.
   * @return the persisted policy plus whether this call created it (true) or replaced an
   *     existing one (false).
   * @throws DelegationPolicyAlreadyExistsException if a concurrent register() for the same actor
   *     is lost after this method's own single internal retry.
   * @throws DelegationPolicyNotFoundException if a concurrent delete() for the same actor is lost
   *     after this method's own single internal retry.
   * @throws RuntimeException on any other storage error.
   */
  RegisterOrUpdateResult registerOrUpdate(DelegationPolicy policy);

  /**
   * @throws DelegationPolicyNotFoundException if registrationId does not exist.
   * @throws RuntimeException on any other storage error.
   */
  void delete(String registrationId);

  Optional<DelegationPolicy> get(String registrationId);

  /** Primary lookup used by evaluate() and by the admin API scope-limiting check. */
  Optional<DelegationPolicy> findByActor(String actorAuthority, String actorId);

  /** @param actorAuthorityFilter null returns all policies */
  DelegationPolicyList list(String actorAuthorityFilter);

  PolicyDecision evaluate(PolicyCheckRequest request);

  /**
   * @return the gateway-wide default token TTL (seconds) that {@link #evaluate} applies when a
   *     policy does not pin its own tokenTtlSec. Exposed so the admin API can validate this
   *     fallback against its configured [min, max] bounds at startup and fail fast on an
   *     out-of-range value -- otherwise policies stored without an explicit tokenTtlSec would
   *     yield an effective TTL outside the range the API enforces for explicit values.
   */
  int getConfiguredTokenTtlSec();
}
